### ISSUE TITLE
ie 8 + 9 do not support classList

### ISSUE THREAD

**Issue by ginsterbusch** [james2doyle/ki.extend.js#4]
according to caniuse.com + MDN, ie 8 + 9 do not support classList. Thus, the classes.js is basically .. broken.

Suggested fallback or replacement: https://github.com/EarMaster/CSSClass (been in use for about a year on my site, till I switched to ki.js last month)
https://gist.github.com/devongovett/1381839 (not tested)

cu, w0lf.

**Comment by james2doyle** [comment]
I don't claim to support oldIE. If you would like to use a polyfill then go ahead. Adding that fallback to the this project would add unneeded bloat. You should serve a polyfill script using a IE conditional comment. 

I have used this one before https://github.com/eligrey/classList.js

**Comment by ginsterbusch** [comment]
Yeah, you dont. But ki.js itself states its supporting IE 9. So you're breaking that support.
And one would not expect that ;)

cu, w0lf.

**Comment by james2doyle** [comment]
You dont use [html5shiv](https://github.com/aFarkas/html5shiv) or [respondjs](https://github.com/scottjehl/Respond)? If you don't use html5shiv you can't even use modern elements. So you have more issues than class toggling.

I'm using `Array.filter` and `Array.map` as well, which aren't supported in < IE 9. So you should be picking and choosing what you need/want, then filling in what is missing. That is why I created the build system that way it is.

I'm assuming you are using Ki because you don't want giant jQuery bloat. I would suggest using ki.js by itself and then writing your own prototype for the class functions. You can be very slim that way.

**Comment by ginsterbusch** [comment]
Neither. I'm using [Head.JS](http://headjs.com/) + [Vanilla JS](http://vanilla-js.com/) ;)

cu, w0lf.
